# 1) Build every commit on every branch and add the COMMIT SHORT SHA as suffix
maven-build:
  stage: build
  tags:
    - shared
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}

# 2) Does a (local) mvn clean install for every tagged commit
release-build:
  stage: deploy
  tags:
    - shared
  script:
    - mvn clean install
  dependencies:
    - maven-build
  artifacts:
    paths:
      - target/*.jar
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}
  only:
    - tags
